version: '3.1'

services:
  backend:
    image: ''
    container_name: ''
    depends_on:
      - pgdb
    environment:
      - SERVER_PORT=9999
      - SPRING_DATA_SOURCE=admin
      - SPRING_DATA_PASSWORD=admin
      - SPRING_DATA_URL=jdbc:postgresql://localhost:5432/postgres

    ports:
      - 8080:9999

  pgdb:
    image: postgres
    container_name: 'pg_container'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432